# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
      
  admin-mongo:
    image: mrvautin/adminmongo
    restart: always
    ports:
      - 8082:1234
    environment:
      CONN_NAME: local-connection
      DB_USERNAME: root
      DB_PASSWORD: example
      DB_HOST: mongo
      DB_NAME: test
      
  # influxdb:
  #   image: influxdb:latest
  #   container_name: influxdb
  #   ports:
  #     - "8083:8083"
  #     - "8086:8086"
  #     - "8090:8090"
  #   volumes:
  #     # Data persistency
  #     # sudo mkdir -p /srv/docker/influxdb/data
  #     - /srv/docker/influxdb/data:/var/lib/influxdb

  # chronograf:
  #   image: chronograf
  #   ports:
  #     - 8081:8888
  #   command: chronograf influxdb-url=http://influxdb:8086

