module.exports = {
    cryptoCurrencies: [
        "BTC",
        "ETH",
        "XRP",
        "EOS",
        "LTC",
        "NEO",
        "IOT",
        "ZEC",
        "ETC",
        "XMR",
        "BSV",
        "DSH",
        "OMG",
        "ETP",
        "BAB",
        // "MGO",
        "ZRX",
        "TRX",
        "XTZ",
        "BTG",
        "XLM",
        "SAN",
        // "DAI",
        "EDO",
        "FUN",
        "XVG",
        "QTM",
        "BAT",
        "QSH",
        "ODE",
        "ELF",
        // "GNT",
        "GOT",
        "ZIL",
        "VET"
        // "RLC",
        // "RRT",
        // "IQX",
        // "MKR",
        // "YYW",
        // "DTH",
        // "REP",
        // "WAX",
        // "PNK",
        // "CNN",
        // "TKN",
        // "RDN",
        // "TNB",
        // "BCI",
        // "SNT",
        // "RCN",
        // "XRA",
        // "UTN",
        // "DGX",
        // "MIT",
        // "AGI",
        // "AVT",
        // "POA",
        // "ANT",
        // "ORS",
        // "NIO",
        // "BFT",
        // "MTN",
        // "CBT",
        // "BBN",
        // "SPK",
        // "WTC",
        // "PAI",
        // "SEE",
        // "CND",
        // "FSN",
        // "ABS",
        // "SEN",
        // "AIO",
        // "HOT",
        // "WPR",
        // "ATM",
        // "LRC",
        // "AID",
        // "BNT",
        // "DTA",
        // "REQ",
        // "CFI",
        // "ESS",
        // "AUC",
        // "UTK",
        // "ZCN",
        // "MLN"
    ],
    mongoDbConnectionString: 'mongodb://localhost/bfx'
}